#+TITLE:Japanese Journal: Language Log: The Sequel
#+AUTHOR:Archenoth
#+EMAIL:Archenoth@gmail.com
:SETTINGS:
#+STARTUP: hidestars
#+DRAWERS: KANA SETTINGS
#+LINK: translate https://translate.google.com/?sl=ja&tl=en&hl=en&q=
#+TAGS: Hiragana(h) Katakana(k) Kanji(g) Study(s) Code(c) drill(d)
#+OPTIONS: ^:nil H:3 p:nil tags:not-in-toc todo:nil toc:nil
#+PROPERTY: header-args :exports both :eval never-export
#+LANGUAGE: jp
#+LATEX_CLASS: japanese
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usemintedstyle{friendly}
#+LATEX_HEADER: \renewcommand{\contentsname}{Table of Contents}
#+TOC: headlines 3
#+LATEX: \pagebreak
:END:

So, I kinda dropped off after my last language log, and I figured I'd fire this up again!

As a recap, here is a list of what each entry should have:
#+BEGIN_QUOTE
*Each entry should have:*
- What you learned.
- How you felt about what you learned (was it frustrating? Easy? etc)
  so you can figure out what causes you trouble and focus on fixing
  that.
- What you need to work on.
- What you want to learn next.
#+END_QUOTE

* <2019-01-14 Mon> Wanikani begins again!
Alright! I've neglected Wanikani for a while, but I already reset once and found that the first levels are pretty easy. So today I reset to level 10. I still have 200 reviews, but hey! At least the reviews aren't mind melting things that neglecting my SRS would have doomed me to. (Also, some Wanikani radicals have changed)

Some choice things I screwed up during my recap were:
| 仮定 | I thought it was かってい with a pause (It's かてい)       |
| 活用 | I completely forgot about "conjugation"                    |
| 体力 | I continue my long tradition of thinking it's きょうりょく |
| 以後 | This means "From now on". "Previously" is 以前             |
| 石   | This one changed on me from いし to せき during the update |
| 投   | This one changed from な to とう also during the update    |

I also have a Japanese 3DS and a few Japanese Pokemon Mystery Dungeon games coming in soon. It'll be cool to get started on those to give me some practical material I can play with--because unlike Pokemon Moon, these games have furigana!

I'm also thinking of approaching Wanikani a little differently now. Mostly relying on gaps in the day to do small sets of 10 reviews whenever possible. This should stop me from getting flooded when I'm doing a bunch of other things.

* <2019-01-24 Thu> Gates to Infinity
Not a whole lot notable happened in since my last entry, it's mostly been just the standard Wanikani practice and keeping up to date with Duolingo.

But!

My Japanese 3DS came in!! and so did my three games!!!

I went through the 3DS setup process, and started working my way through Gates to Infinity, and am keeping another Org file with its translation.
I'm not sure if I'll put it up somewhere like with Pokemon Green, as it's mostly going to be assuming you have my exact level of knowledge for the places I noted things, and the words I added Jisho links for.

Needless to say, Pokemon Mystery Dungeon: Gates to Infinity is going to be my background music for a long time.
I wonder if I'll beat Mystery Dungeon before the next one is out next millennium?

Today I played for quite a lot of time (At least, until the 3DS battery was getting low) and I learned about "だろう" being used like "だ", except expressing strong uncertainty, and also about "くる" being used on て-form verbs to indicate something coming into your perspective.

I also think I knew this one once, but I relearned "と見える" as meaning "It seems that" when used as a sentence-ender. Same for "やっぱり", which means "Like I thought".

I also decided to install a bunch of Wanikani userscripts (In addition to Ultimate Timeline), so now I can more readily see things like my leeches. Maybe I'll put those here if they turn out to be useful!

...ah, it's not for the ones you just reviewed, it's just in general. Though I guess it would be a good idea to watch out for 欠ける, which means "To lack".

What a strange thing to miss so often--oh wait, maybe that's why I confuse it with that? Oops.
