#+TITLE:Japanese Journal: Language Log: The Sequel
#+AUTHOR:Archenoth
#+EMAIL:Archenoth@gmail.com
:SETTINGS:
#+STARTUP: hidestars
#+DRAWERS: KANA SETTINGS
#+LINK: translate https://translate.google.com/?sl=ja&tl=en&hl=en&q=
#+TAGS: Hiragana(h) Katakana(k) Kanji(g) Study(s) Code(c) drill(d)
#+OPTIONS: ^:nil H:3 p:nil tags:not-in-toc todo:nil toc:nil
#+PROPERTY: header-args :exports both :eval never-export
#+LANGUAGE: jp
#+LATEX_CLASS: japanese
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usemintedstyle{friendly}
#+LATEX_HEADER: \renewcommand{\contentsname}{Table of Contents}
#+TOC: headlines 3
#+LATEX: \pagebreak
:END:

So, I kinda dropped off after my last language log, and I figured I'd fire this up again!

As a recap, here is a list of what each entry should have:
#+BEGIN_QUOTE
*Each entry should have:*
- What you learned.
- How you felt about what you learned (was it frustrating? Easy? etc)
  so you can figure out what causes you trouble and focus on fixing
  that.
- What you need to work on.
- What you want to learn next.
#+END_QUOTE

* <2019-01-14 Mon> Wanikani begins again!
Alright! I've neglected Wanikani for a while, but I already reset once and found that the first levels are pretty easy. So today I reset to level 10. I still have 200 reviews, but hey! At least the reviews aren't mind melting things that neglecting my SRS would have doomed me to. (Also, some Wanikani radicals have changed)

Some choice things I screwed up during my recap were:
| 仮定 | I thought it was かってい with a pause (It's かてい)       |
| 活用 | I completely forgot about "conjugation"                    |
| 体力 | I continue my long tradition of thinking it's きょうりょく |
| 以後 | This means "From now on". "Previously" is 以前             |
| 石   | This one changed on me from いし to せき during the update |
| 投   | This one changed from な to とう also during the update    |

I also have a Japanese 3DS and a few Japanese Pokemon Mystery Dungeon games coming in soon. It'll be cool to get started on those to give me some practical material I can play with--because unlike Pokemon Moon, these games have furigana!

I'm also thinking of approaching Wanikani a little differently now. Mostly relying on gaps in the day to do small sets of 10 reviews whenever possible. This should stop me from getting flooded when I'm doing a bunch of other things.
